site_name: Assimilator - the best Python patterns
site_description: Assimilator Python framework, Domain-Driven Design, DDD, high performance, easy to learn, fast to code
theme:
  name: material
  custom_dir: docs/docs_theme
  logo: images/logo.png
  favicon: images/icon.png
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.footer
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
nav:
  - Introduction: index.md
  - Concepts: concepts.md
  - Basic tutorials:
    - Important things: tutorial/important.md
    - Database tutorial: tutorial/database.md
    - Advanced database tutorial: tutorial/advanced_database.md
    - Architecture tutorial: tutorial/architecture_tutorial.md
    # - Events tutorial: tutorial/events.md
  - SQLAlchemy:
    - Database: alchemy/database.md
    # - Events: alchemy/events.md
  - Internal:
    - Database: internal/database.md
    # - Events: internal/events.md
  # - Kafka:
    # - Events: kafka/events.md
  - Redis:
    - Database: redis/database.md
    # - Events: redis/events.md
  - MongoDB:
    - Database: mongo/database.md
  - Services Tutorial: services.md
  - Unidentified Patterns: unidentified_patterns.md
  - Video Tutorials: video_tutorials.md
  - Help us make the futureðŸ¤©: help_framework.md
  - âœ¨New in 1.2.0âœ¨: new_changes.md
  - ðŸ•¢Next updateðŸ•¢: next_update.md

repo_url: https://github.com/knucklesuganda/py_assimilator
repo_name: knucklesuganda/py_assimilator
site_author: Andrey Ivanov | Python
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-7PEMV9YSS5
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  extra:
    social:
      - icon: fontawesome/solid/paper-plane
        link: mailto:python.on.papyrus@gmail.com
copyright: Copyright &copy; 2023 Andrey Ivanov
extra_javascript:
  - https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8262462913055533
  - scripts/add_footer.js
  - scripts/feedback.js
